title: "Aparajitha Ramesh"
description: "My academic website"
remote_theme: jekyll-theme-cayman

# Navigation menu
navbar_links:
  Home: /
  Publications: /publications
  News: /news
  Contact: /contact
  Others: /others
